version: '3.4'

services:
  webalertapi:
    build:
      context: .
      dockerfile: WebAlertApi/Dockerfile
      target: runtime  # This uses the runtime stage for WebAlertApi
    ports:
      - "8083:8083"
  
  queuemessagesystem:
    build:
      context: .
      dockerfile: QueueMessageSystem/Dockerfile
      target: runtime  # This uses the runtime stage for QueueMessageSystem
    ports:
      - "8081:8081"
